/**
 * Reasoning orchestration: attempt, validate, repair once, else fall back.
 *
 * The generator is INJECTED, so this module performs no I/O of its own and
 * holds no SDK dependency — the retry and fallback state machine is fully
 * testable with a scripted function and never touches a network.
 *
 * THE SYSTEM MUST NEVER STALL BECAUSE THE MODEL FAILED. Every path through this
 * function returns a usable proposal; the only question is whether it is
 * labelled LLM or DETERMINISTIC_FALLBACK, and that label is surfaced to the
 * merchant rather than hidden.
 */
import { buildRepairPrompt, buildUserPrompt } from "./prompt";
import type {
  LlmDecision,
  ReasonedProposal,
  ReasonerCandidate,
  ReasonerInput,
  ReasoningAttempt,
  ValidationOutcome,
} from "./types";
import { validateLlmResponse } from "./validator";

/** What an injected generator must return. */
export interface GenerateResult {
  text: string | null;
  latencyMs: number;
  inputTokens?: number;
  outputTokens?: number;
}

export type GenerateFn = (prompt: string) => Promise<GenerateResult>;

export interface ReasonOptions {
  /** Attempt a single repair when the first response is rejected. Default true. */
  allowRepair?: boolean;
}

/**
 * Strict argmax(expectedNetPaise), with a total ordering so the result cannot
 * depend on input order. This is the ONLY place a winner is chosen
 * deterministically, and it lives outside the estimator on purpose.
 */
export function selectByHighestExpectedNet(
  candidates: readonly ReasonerCandidate[],
): ReasonerCandidate {
  if (candidates.length === 0) {
    throw new Error("Cannot reason over an empty candidate set");
  }
  return [...candidates].sort(
    (a, b) =>
      b.expectedNetPaise - a.expectedNetPaise || a.playbookId.localeCompare(b.playbookId),
  )[0]!;
}

const FALLBACK_RATIONALE =
  "LLM reasoning was unavailable. The deterministic fallback selected the candidate " +
  "with the highest expected net revenue.";

/**
 * System-authored proposal used when the model cannot be trusted or reached.
 *
 * The copy is deliberately plain and carries no figures: nothing here was
 * reasoned about, and it should not pretend otherwise.
 */
export function buildDeterministicFallback(
  input: ReasonerInput,
  attempts: readonly ReasoningAttempt[],
  reason: string,
): ReasonedProposal {
  const selected = selectByHighestExpectedNet(input.candidates);

  return {
    selectedPlaybookId: selected.playbookId,
    selectedCandidate: selected,
    rationale: `${FALLBACK_RATIONALE} ${reason}`.trim(),
    customerMessage: {
      subject: "Completing your recent payment",
      body:
        "Hello,\n\nYour recent payment of {{amount}} did not go through. " +
        "You can complete it using the link below whenever convenient.\n\n" +
        "{{payment_link}}\n\nIf you have already paid, please ignore this message.\n\n" +
        "Thank you.",
    },
    risksIdentified: [
      "Proposal was generated by deterministic fallback, without model reasoning.",
      "Customer-facing copy is a system default and has not been reviewed for tone.",
      `Candidate confidence is ${selected.confidence}; priors carry no recorded outcomes yet.`,
    ],
    confidenceNote:
      `Selected strictly by highest expected net revenue. Estimator confidence is ` +
      `${selected.confidence}. No model reasoning contributed to this proposal.`,
    reasoningMode: "DETERMINISTIC_FALLBACK",
    attempts,
  };
}

function toProposal(
  decision: LlmDecision,
  selected: ReasonerCandidate,
  attempts: readonly ReasoningAttempt[],
): ReasonedProposal {
  return {
    selectedPlaybookId: decision.selectedPlaybookId,
    selectedCandidate: selected,
    rationale: decision.rationale,
    customerMessage: decision.customerMessage,
    risksIdentified: decision.risksIdentified,
    confidenceNote: decision.confidenceNote,
    reasoningMode: "LLM",
    attempts,
  };
}

/** Human-readable summary of why a fallback happened, for the audit trail. */
function describeOutcome(outcome: ValidationOutcome, detail?: string): string {
  const base: Record<ValidationOutcome, string> = {
    VALID: "Response was valid.",
    EMPTY_RESPONSE: "The model returned no content.",
    MALFORMED_JSON: "The model returned output that was not valid JSON.",
    SCHEMA_INVALID: "The model's output did not match the required schema.",
    UNKNOWN_PLAYBOOK: "The model selected a playbook that was not offered.",
    NUMERIC_HALLUCINATION: "The model stated a figure the estimator did not produce.",
    UNSUPPORTED_MESSAGE_CLAIM: "The customer message contained an unsupported financial claim.",
    CONFIDENCE_OVERCLAIM: "The model claimed more confidence or evidence than is supported.",
    PROVIDER_ERROR: "The model provider could not be reached.",
  };
  return detail ? `${base[outcome]} (${detail})` : base[outcome];
}

/**
 * Produce a proposal for one opportunity.
 *
 * Never throws for a model-side problem: a provider outage, a malformed
 * response, or a fabricated number all end in a labelled fallback rather than
 * an error. The only fatal condition is an empty candidate set, which would
 * mean the estimator had produced nothing to choose between.
 */
export async function reasonOverCandidates(
  input: ReasonerInput,
  generate: GenerateFn,
  options: ReasonOptions = {},
): Promise<ReasonedProposal> {
  if (input.candidates.length === 0) {
    throw new Error("Cannot reason over an empty candidate set");
  }

  const allowRepair = options.allowRepair ?? true;
  const attempts: ReasoningAttempt[] = [];

  const runAttempt = async (
    prompt: string,
    attemptNo: number,
    kind: "INITIAL" | "REPAIR",
  ): Promise<ReasoningAttempt> => {
    try {
      const result = await generate(prompt);
      const validation = validateLlmResponse(result.text, input);
      return {
        attemptNo,
        kind,
        prompt,
        rawResponse: result.text,
        latencyMs: result.latencyMs,
        ...(result.inputTokens === undefined ? {} : { inputTokens: result.inputTokens }),
        ...(result.outputTokens === undefined ? {} : { outputTokens: result.outputTokens }),
        outcome: validation.ok ? "VALID" : validation.outcome,
        isValid: validation.ok,
        issues: validation.ok ? [] : validation.issues,
        parsedOutput: validation.ok ? validation.decision : null,
      };
    } catch (error) {
      // A provider failure is an expected operating condition, not a crash.
      return {
        attemptNo,
        kind,
        prompt,
        rawResponse: null,
        latencyMs: 0,
        outcome: "PROVIDER_ERROR",
        isValid: false,
        issues: [
          {
            outcome: "PROVIDER_ERROR",
            field: "provider",
            message: (error as Error).message,
          },
        ],
        parsedOutput: null,
        errorMessage: (error as Error).message,
      };
    }
  };

  const first = await runAttempt(buildUserPrompt(input), 1, "INITIAL");
  attempts.push(first);

  if (first.isValid && first.parsedOutput) {
    const selected = input.candidates.find(
      (c) => c.playbookId === first.parsedOutput!.selectedPlaybookId,
    )!;
    return toProposal(first.parsedOutput, selected, attempts);
  }

  // A provider that could not be reached will not be reached by rephrasing.
  const repairable = allowRepair && first.outcome !== "PROVIDER_ERROR";
  if (!repairable) {
    return buildDeterministicFallback(
      input,
      attempts,
      describeOutcome(first.outcome, first.errorMessage),
    );
  }

  const second = await runAttempt(buildRepairPrompt(input, first.issues), 2, "REPAIR");
  attempts.push(second);

  if (second.isValid && second.parsedOutput) {
    const selected = input.candidates.find(
      (c) => c.playbookId === second.parsedOutput!.selectedPlaybookId,
    )!;
    return toProposal(second.parsedOutput, selected, attempts);
  }

  return buildDeterministicFallback(
    input,
    attempts,
    `${describeOutcome(first.outcome)} Repair attempt also failed: ` +
      `${describeOutcome(second.outcome, second.errorMessage)}`,
  );
}
